### ISSUE TITLE
Wrong assertion

### ISSUE THREAD

**Issue by EinsimplerGeist** [koerihub/koeri-tests#7]
As far as i can see this assertion is incorrect and should return false:
https://github.com/koerihub/koeri-tests/blob/34bba8c6d420abf08a1353f7f74c46e8b2ccfada/src/test/java/edu/kit/informatik/Acul021NetworkTest.java#L56
Especially if this should return false:
https://github.com/koerihub/koeri-tests/blob/34bba8c6d420abf08a1353f7f74c46e8b2ccfada/src/test/java/edu/kit/informatik/Acul021NetworkTest.java#L52

**Comment by koerihub** [comment]
The assertion in line 52 is correct because the subnet is already fully contained in the network. On the other hand, line 56 adds one new node (`2.2.2.2`) to the network.
