### ISSUE TITLE
NullPointerExcetipns in probes for null

### ISSUE THREAD

**Issue by EinsimplerGeist** [koerihub/koeri-tests#8]
https://github.com/koerihub/koeri-tests/blob/34bba8c6d420abf08a1353f7f74c46e8b2ccfada/src/test/java/edu/kit/informatik/util/KoeriTestUtils.java#L71

This line generates a lot of nullpointer errors when we probe for null

**Comment by koerihub** [comment]
Please make sure to run the tests correctly using `./gradlew test` so that the files in `/src/test/resources` are accessible via the class loader.
